<a href="https://colab.research.google.com/github/incredible2003/-Sales-Dashboard-Power-BI-Project-/blob/main/Numpy_practicse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# create array using tuple
n= np.array((1,2,3,4,5))
print (n)
print(type(n))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
# create array using list
n= np.array([1,2,3,4,5])
print (n)
print(type(n))


In [2]:
import numpy as np
# create array using tuple
n= np.array((1,2,3,4,5))
print (n)
print(type(n))
print("\n Diamenson = ",n.ndim)


[1 2 3 4 5]
<class 'numpy.ndarray'>

 Diamenson =  1


In [3]:
import numpy as np
# create array using tuple
n= np.array(([1,2,4,5],[5,6,9,8]))
print (n)
print(type(n))
print("Diamenson Array",n.ndim)


[[1 2 4 5]
 [5 6 9 8]]
<class 'numpy.ndarray'>
Diamenson Array 2


In [5]:
import numpy as np
# create array using tuple
n= np.zeros([3,3])
print (n)
print(type(n))
print("Array 3 diamenson",n.ndim)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
Array 3 diamenson 2


In [6]:
import numpy as np
# create array using tuple
n= np.array(([1,2,3,4,5]))
print (n)
print(type(n))
print(n.dtype)


[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [7]:
import numpy as np
# create array using tuple
n= np.array((['Atul ','Anu','Richa','Anil']))
print (n)
print(type(n))
print(n.dtype)

['Atul ' 'anu' 'Richa' 'Anil']
<class 'numpy.ndarray'>
<U5


In [8]:
import numpy as np
# create array using tuple
n= np.array(([1,2,5],[5,9,6]))
print (n)
print(type(n))
print(n.dtype)
# array using indexing no  element accesing
print(n[0,0])
print(n[0,1])
print(n[0,2])

[[1 2 5]
 [5 9 6]]
<class 'numpy.ndarray'>
int64
1
2
5


In [11]:
import numpy as np
# create array using tuple
n= np.array(([1,2,5],[5,9,6]))
print (n)
print(type(n))
print(n.dtype)
# array using indexing no  element accesing
print(n[1,0])
print(n[1,1])
print(n[1,2])

[[1 2 5]
 [5 9 6]]
<class 'numpy.ndarray'>
int64
5
9
6


In [15]:
import numpy as np
# create array using tuple
n= np.array(([1,2,5],[5,9,6],[22,23,43]))
print (n)
print(type(n))
print(n.dtype)
# array using indexing no  element accesing


[[ 1  2  5]
 [ 5  9  6]
 [22 23 43]]
<class 'numpy.ndarray'>
int64


In [10]:
import numpy as np
n= np.array([12,13,15,17,19])
# Acessing element from arary to any diamnsonal
print (n)
print(n[4])




[12 13 15 17 19]
19


In [16]:
import numpy as np
n= np.array([12,13,15,17,19])
# Acessing element from arary to any diamnsonal
print (n)
print("elemnt of no as = ",n[-1])

[12 13 15 17 19]
elemnt of no as =  19


In [19]:
import numpy as np
n= np.array([[12,13,15],[23,33,44]])
# Acessing element from arary to any diamnsonal
print (n)
print("\n last element mo =",n[0,-1])
print("\n last element mo =",n[1,-1])

[[12 13 15]
 [23 33 44]]

 last element mo = 15

 last element mo = 44


In [20]:
# Array slicing practicse
import numpy as np
n= np.array([12,13,15,17,19,45,56,67])
# Acessing element from arary to any diamnsonal
print (n[1:3])

[13 15]


In [21]:
# Array slicing practicse
import numpy as np
n= np.array([12,13,15,17,19,45,56,67])
# Acessing element from arary to any diamnsonal
print (n[2:5])

[15 17 19]


In [22]:
# Array slicing practicse
import numpy as np
n= np.array([12,13,15,17,19,45,56,67])
# Acessing element from arary to any diamnsonal
print (n[5:])

[45 56 67]


In [23]:
# Array slicing practicse
import numpy as np
n= np.array([12,13,15,17,19,45,56,67,60,89,90,99])
# Acessing element from arary to any diamnsonal
print (n[1:10:2])

[13 17 45 67 89]


In [24]:
# Join array using the concatinate fun
import numpy as np
n1 = np.array([2,13,15])
n2 = np.array([2,11,19])
print ("iterating array")
for a in  n1:
  print(a)
  print("iterating array n2")
  for a  in n2:
    print (a)
    resume= np.concatenate((n1,n2))
    print ("After join the array",resume)


iterating array
2
iterating array n2
2
After join the array [ 2 13 15  2 11 19]
11
After join the array [ 2 13 15  2 11 19]
19
After join the array [ 2 13 15  2 11 19]
13
iterating array n2
2
After join the array [ 2 13 15  2 11 19]
11
After join the array [ 2 13 15  2 11 19]
19
After join the array [ 2 13 15  2 11 19]
15
iterating array n2
2
After join the array [ 2 13 15  2 11 19]
11
After join the array [ 2 13 15  2 11 19]
19
After join the array [ 2 13 15  2 11 19]


In [25]:
# Join array using the concatinate fun
import numpy as np
n1 = np.array([2,13,15])
n2 = np.array([2,11,19])
print ("iterating array")
for a in  n1:
  print(a)
  print("iterating array n2")
  for a  in n2:
    print (a)
    resume= np.stack((n1,n2),axis =1)

    print ("After join the array",resume)


iterating array
2
iterating array n2
2
After join the array [[ 2  2]
 [13 11]
 [15 19]]
11
After join the array [[ 2  2]
 [13 11]
 [15 19]]
19
After join the array [[ 2  2]
 [13 11]
 [15 19]]
13
iterating array n2
2
After join the array [[ 2  2]
 [13 11]
 [15 19]]
11
After join the array [[ 2  2]
 [13 11]
 [15 19]]
19
After join the array [[ 2  2]
 [13 11]
 [15 19]]
15
iterating array n2
2
After join the array [[ 2  2]
 [13 11]
 [15 19]]
11
After join the array [[ 2  2]
 [13 11]
 [15 19]]
19
After join the array [[ 2  2]
 [13 11]
 [15 19]]


In [29]:
import numpy as np
n= np.array([[12,13,15,],[19,45,56],[67,60,89]])
# Acessing element from arary to any diamnsonal
print("iterating 2d array ....")
for a in n:
  print(a)

print("scored by  2d \n ", np.sort(n))

iterating 2d array ....
[12 13 15]
[19 45 56]
[67 60 89]
scored by  2d 
  [[12 13 15]
 [19 45 56]
 [60 67 89]]
